### ISSUE TITLE
esm.sh is also unstable

### ISSUE THREAD

**Issue by kachick** [kachick/depop#143]
```
error: Integrity check failed for remote specifier. The source code is invalid, as it does not match the expected hash in the lock file.

  Specifier: https://esm.sh/stable/react@18.2.0/denonext/jsx-runtime.js
  Actual: 309faa58fa4e914707daffa1a9514bef4593c952f930640cf93bb871aab7ceb6
  Expected: 54d8a51c6ca025380abd2d5302e4a9b38ff835d9759c4657e52314f587eaf6bf

This could be caused by:
  * the lock file may be corrupt
  * the source itself may be corrupt

Use the --lock-write flag to regenerate the lockfile or --reload to reload the source code from the server.
```

https://github.com/kachick/depop/pull/43

=>

https://github.com/kachick/depop/pull/142
https://github.com/kachick/depop/actions/runs/10691797035/job/29644832809

---

How about replacing it with JSR?

Or I might wrongly understand something about them...? 🤔

**Comment by kachick** [comment]
https://github.com/esm-dev/esm.sh/issues/519
https://github.com/esm-dev/esm.sh/issues/614

**Comment by kachick** [comment]
https://esm.sh/#docs

>Pinning Build Version

At least I wish to try this first...

**Comment by kachick** [comment]
https://github.com/esm-dev/esm.sh/releases 🤔 However they didn't update the esm.sh version v135 since 2023...

**Comment by kachick** [comment]
No react in JSR https://github.com/facebook/react/issues/28971

**Comment by kachick** [comment]
https://docs.deno.com/runtime/fundamentals/modules/

**Comment by kachick** [comment]
When using newewr deno

```
Warning "--lock-write" flag is deprecated and will be removed in Deno 2
```

**Comment by kachick** [comment]
https://zenn.dev/hashrock/scraps/9e9eb8620553f7#comment-c3aa6188e61995

**Comment by ije** [comment]
i think the lock file break caz https://github.com/esm-dev/esm.sh/issues/874, fyi the next version v136, which i still working on it, as removed the `/v135` and `/stable` prefix, that means we do not build modules everytime we deploy the new version that breaks deno.lock

**Comment by kachick** [comment]
Thank you for sharing it with me! :pray:
